In [3]:
import pandas as pd
dir = 'F:\diabetese-dataset\Dengue.xlsx'
df = pd.read_excel(dir)
df

date_week       date      rain      Tair        rh  Mean_EVI  lncase_0  \
0       201301 2012-12-30  0.195273  0.643833  0.491234  0.222167  3.496508   
1       201302 2013-01-06  0.000441  0.679941  0.452052  0.581625  4.382027   
2       201303 2013-01-13  0.006073  0.757157  0.528279  0.708618  4.682131   
3       201304 2013-01-20  0.006922  0.628925  0.613447  0.683476  4.691348   
4       201305 2013-01-27  0.056071  0.649667  0.416352  0.722145  5.023881   
..         ...        ...       ...       ...       ...       ...       ...   
413     202049 2020-11-29  0.002675  0.593175  0.569991  0.754052  4.521789   
414     202050 2020-12-06  0.019823  0.561818  0.519115  0.625111  4.290459   
415     202051 2020-12-13  0.011249  0.586876  0.544007  0.703703  4.406719   
416     202052 2020-12-20  0.023800  0.533037  0.532567  0.638070  3.637586   
417     202053 2020-12-27  0.000176  0.595330  0.530835  0.805380  3.737670   

     lncase_1  lncase_2  lncase_3  lncase_4  
0    4.382027  4.682131  4.691348  5.023881  
1    4.682131  4.691348  5.023881  4.983607  
2    4.691348  5.023881  4.983607  4.787492  
3    5.023881  4.983607  4.787492  5.411646  
4    4.983607  4.787492  5.411646  5.777652  
..        ...       ...       ...       ...  
413  4.290459  4.406719  3.637586  3.737670  
414  4.406719  3.637586  3.737670  3.687628  
415  3.637586  3.737670  3.687628  3.712649  
416  3.737670  3.687628  3.687628  3.700138  
417  4.487134  3.687628  3.704308  3.706394  

[418 rows x 11 columns]

In [4]:
import numpy as np

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
df1= scaler.fit_transform(np.array(df[['rain','Tair','rh','Mean_EVI','lncase_0','lncase_1','lncase_2','lncase_3','lncase_4']]).reshape(-1,1))
#scaler.fit_transform(np.array(df['lncase_1']).reshape(-1,1))
#scaler.fit_transform(np.array(df['lncase_2']).reshape(-1,1))
#scaler.fit_transform(np.array(df['lncase_3']).reshape(-1,1))
#scaler.fit_transform(np.array(df['lncase_4']).reshape(-1,1))

In [6]:
df1.shape

(3762, 1)

In [7]:
training_size= int(len(df1)*0.7)


In [8]:
test_size = len(df1)-training_size


In [9]:
training_size,test_size

(2633, 1129)

In [10]:
train_data,test_data=df1[0:training_size,:],df1[training_size:len(df1),:1]

In [11]:
import numpy
#convert an array of values into dataset matrix
def create_dataset(dataset,time_step=1):
    dataX,dataY = [], []
    for i in range (len(dataset)-time_step-1):
        a = dataset[i:(i+time_step),0]
        dataX.append(a)
        dataY.append(dataset[i + time_step ,0])
    return numpy.array(dataX), numpy.array(dataY)

In [12]:
# reshape
time_step = 4
X_train, y_train = create_dataset(train_data, time_step)
X_test,y_test= create_dataset(test_data, time_step)

In [13]:
print(X_train)

[[0.02336432 0.07703444 0.05877603 0.02658228]
 [0.07703444 0.05877603 0.02658228 0.41835621]
 [0.05877603 0.02658228 0.41835621 0.52430833]
 ...
 [0.48375002 0.46565527 0.41835621 0.00445375]
 [0.46565527 0.41835621 0.00445375 0.05582641]
 [0.41835621 0.00445375 0.05582641 0.06074062]]


In [14]:
print(X_test.shape),print(y_test.shape)

(1124, 4)
(1124,)


(None, None)

In [15]:
X_train = X_train.reshape(X_train.shape[0],X_train.shape[1], 1)
X_test =  X_test.reshape(X_test.shape[0],X_test.shape[1], 1)

In [1]:
#!pip install tensorflow

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
scipy 1.7.1 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.3 which is incompatible.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.24.3 which is incompatible.
label-studio 1.6.0 requires google-auth==2.11.0, but you have google-auth 2.22.0 which is incompatible.



  Using cached tensorflow-2.13.0-cp39-cp39-win_amd64.whl (1.9 kB)
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.11.0
    Uninstalling google-auth-2.11.0:
      Successfully uninstalled google-auth-2.11.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3


In [25]:
#creating lstm model

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Sequential

In [26]:
model = Sequential()
model.add(LSTM(50,return_sequences = True, input_shape=(4,1)))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer ='adam')

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 4, 50)             10400     
                                                                 
 lstm_1 (LSTM)               (None, 4, 50)             20200     
                                                                 
 lstm_2 (LSTM)               (None, 50)                20200     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 50851 (198.64 KB)
Trainable params: 50851 (198.64 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs =100, batch_size=64,verbose=1)

Epoch 1/100
42/42 [==============================] - 15s 94ms/step - loss: 0.1550 - val_loss: 0.0811
Epoch 2/100
42/42 [==============================] - 1s 31ms/step - loss: 0.0931 - val_loss: 0.0719
Epoch 3/100
42/42 [==============================] - 2s 40ms/step - loss: 0.0704 - val_loss: 0.0496
Epoch 4/100
42/42 [==============================] - 2s 36ms/step - loss: 0.0570 - val_loss: 0.0371
Epoch 5/100
42/42 [==============================] - 1s 32ms/step - loss: 0.0458 - val_loss: 0.0300
Epoch 6/100
42/42 [==============================] - 2s 39ms/step - loss: 0.0415 - val_loss: 0.0319
Epoch 7/100
42/42 [==============================] - 1s 33ms/step - loss: 0.0382 - val_loss: 0.0347
Epoch 8/100
42/42 [==============================] - 1s 35ms/step - loss: 0.0374 - val_loss: 0.0303
Epoch 9/100
42/42 [==============================] - 2s 43ms/step - loss: 0.0379 - val_loss: 0.0290
Epoch 10/100
42/42 [==============================] - 1s 29ms/step - loss: 0.0396 - val_loss: 0.028

In [29]:
#prediction and chacking performance matrics
train_predict=model.predict(X_train)
test_predict = model.predict(X_test)

36/36 [==============================] - 0s 6ms/step


In [31]:
#reversing scaler from
train_predict=scaler.inverse_transform(train_predict)
test_predict=scaler.inverse_transform(test_predict)

In [32]:
#calculating Root mean square error-RMSE performance matrics
import math
from sklearn.metrics import mean_squared_error
math.sqrt(mean_squared_error(y_train,train_predict))

3.4932112227068357

In [33]:
math.sqrt(mean_squared_error(y_test,test_predict))

3.2649269349280234

In [37]:
x_input=test_data[341:].reshape(1,-1)
x_input.shape

(1, 788)

In [38]:
temp_input=list(x_input)
temp_input=temp_input[0].tolist()

In [ ]:
#predicting weekly case
from numpy import array
